### ISSUE TITLE
Какого Хера ???

### ISSUE THREAD

**Issue by NikitaBitRu** [13Anonymous37/bitgen-v3#1]
BitGen by congrammer for https://t.me/ch_anon
Скорость генирации : ~360000/час ~8640000/день
У тебя походу бан по ip

**Comment by K1llmer** [comment]
У меня также

**Comment by serber159rus** [comment]
> BitGen by congrammer for https://t.me/ch_anon
> Скорость генирации : ~360000/час ~8640000/день
> У тебя походу бан по ip

У меня тоже бан по ip на на двух пк в одно время вылез. Пару мин поработало

**Comment by K1llmer** [comment]
Автор походу что то с исходным кодом не так

**Comment by 13Anonymous37** [comment]
Смени прокси
