### ISSUE TITLE
Крадет логи/Steals logs

### ISSUE THREAD

**Issue by lollZio** [13Anonymous37/bitgen-v3#2]
Скрипт сдеалн так,что вы ничего не получите!Автор сделал так,что бы wer кошельки отправлялись ему в телеграм,а не вам.
Script made so that you do not get anything! The author has made it so that the wallets would be sent to him in Telegram, not you.

**Comment by Namig09** [comment]
> Скрипт сдеалн так, что вы ничего не получите! Автор сделал так, что бы wer кошельки отправлялись ему в телеграм, а не вам.
> Скрипт сделан так, что вы ничего не получите! Автор сделал так, чтобы кошельки в Telegram отправлялись ему, а не вам.

Ты разбераешься?
